<?php
/**
 * Copyright (c) 2016. On Tap Networks Limited.
 */
// @codingStandardsIgnoreFile
/* @var OnTap\MasterCard\Block\Threedsecure\Form $block */
?>
<!doctype html>
<html>
<head>
    <title>
        <?php echo __('Process Secure Payment') ?>
    </title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="<?php echo __('Process Secure Payment') ?>" />
    <meta name="robots" content="noindex" />
    <style type="text/css">
        body {font-family:"Trebuchet MS",sans-serif; background-color: #FFFFFF; }#msg {border:5px solid #666; background-color:#fff; margin:20px; padding:25px; max-width:40em; -webkit-border-radius: 10px; -khtml-border-radius: 10px; -moz-border-radius: 10px; border-radius: 10px;}#submitButton { text-align: center ; }#footnote {font-size:0.8em;}
    </style>
</head>
<?php if (!$block->getData('acsUrl') || !$block->getData('paReq')): ?>
    <body>
        <p><?php echo __("Data error") ?></p>
    </body>
<?php else: ?>
    <body onload="return window.document.echoForm.submit()">
        <form name="echoForm" method="post" action="<?php echo $block->getData('acsUrl') ?>" accept-charset="UTF-8" id="echoForm">
            <input type="hidden" name="PaReq" value="<?php echo $block->getData('paReq') ?>" />
            <input type="hidden" name="TermUrl" value="<?php echo $block->escapeUrl($block->getReturnUrl()) ?>" />
            <input type="hidden" name="MD" value="" />
            <noscript>
                <div id="msg">
                    <div id="submitButton">
                        <input type="submit" value="<?php echo __('Click here to continue') ?>" class="button" />
                    </div>
                </div>
            </noscript>
        </form>
    </body>
<?php endif; ?>
</html>
