<?php
    /** @var \Magento\Checkout\Block\Onepage\Link $block */
?>
<button type="button"
        data-role="proceed-to-checkout"
        title="<?= /* @escapeNotVerified */ __('Place Order') ?>"
        data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"<?= /* @escapeNotVerified */ $block->getCheckoutUrl() ?>"}}'
        class="action primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
        <?php if ($block->isDisabled()):?>disabled="disabled"<?php endif; ?>>
    <span><?= /* @escapeNotVerified */ __('Place Order') ?></span>
</button>
