<?php
    /** @var \OnTap\MasterCard\Block\Checkout\Review\PlaceOrder $block */
?>
<ul id="mpgs-checkout-review-place-order" data-bind="scope:'mpgs-checkout-review-place-order'" data-role="content" class="checkout methods items checkout-methods-items">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#mpgs-checkout-review-place-order": {
                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
            }
        }
    </script>
</ul>
