stages:
  - build
  - test

cache:
  paths:
    - .cache/

variables:
  COMPOSER_MIRROR_PATH_REPOS: 1
  COMPOSER_ALLOW_SUPERUSER: 1
  COMPOSER_MEMORY_LIMIT: -1
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.cache/composer"

build:magento-2.3:
  image: ontap/php:7.3
  stage: build
  artifacts:
    paths:
      - _build/
    expire_in: 1 hour
  only:
    - branches
  script:
    - mkdir -p _build/magento
    - git clone . _build/module
    - (cd _build/module && git checkout -b build && sed -i '/"version"/d' composer.json)
    - cd _build/magento
    - composer.phar create-project --no-install --repository=https://repo.magento.com/ magento/project-community-edition:2.3.5 .
    - composer.phar config repositories.ontap composer https://packages.ontapgroup.com/
    - composer.phar config repositories.modules path $CI_PROJECT_DIR/_build/module
    - composer.phar require --dev --no-update --no-suggest ontap/ambassador:^1.0
    - composer.phar config minimum-stability dev
    - composer.phar config prefer-stable true
    - composer.phar require --no-update --no-suggest ontap/module-mastercard:dev-build
    - composer.phar install --no-progress --no-suggest --optimize-autoloader
    - php ./vendor/bin/install-ambassador

build:magento-2.4:
    image: ontap/php:7.3
    stage: build
    artifacts:
        paths:
            - _build/
        expire_in: 1 hour
    only:
        - branches
    script:
        - mkdir -p _build/magento
        - git clone . _build/module
        - (cd _build/module && git checkout -b build && sed -i '/"version"/d' composer.json)
        - cd _build/magento
        - composer.phar create-project --no-install --repository=https://repo.magento.com/ magento/project-community-edition:2.4.0 .
        - composer.phar config repositories.ontap composer https://packages.ontapgroup.com/
        - composer.phar config repositories.modules path $CI_PROJECT_DIR/_build/module
        - composer.phar require --dev --no-update --no-suggest ontap/ambassador:^1.0
        - composer.phar config minimum-stability dev
        - composer.phar config prefer-stable true
        - composer.phar require --no-update --no-suggest ontap/module-mastercard:dev-build
        - composer.phar install --no-progress --no-suggest --optimize-autoloader
        - php ./vendor/bin/install-ambassador

test:phpcs:
  image: ontap/php:7.3
  stage: test
  only:
    - branches
  script:
    - cd _build/magento
    - make phpcs

test:phpstan:
  image: ontap/php:7.3
  stage: test
  only:
    - branches
  script:
    - cd _build/magento
    - make phpstan

test:compile:
  image: ontap/php:7.3
  stage: test
  only:
    - branches
  script:
    - cd _build/magento
    - php bin/magento module:enable --all
    - php -d memory_limit=1G bin/magento setup:di:compile --ansi --no-interaction
