before_script:
  - bash ci/docker_install.sh > /dev/null

cache:
  paths:
    - vendor/

test:7.3:
  image: php:7.3-cli-stretch
  only:
    - branches
  script:
    - COMPOSER_ALLOW_SUPERUSER=1 make test

test:7.2:
  image: php:7.2-cli-stretch
  only:
    - branches
  script:
    - COMPOSER_ALLOW_SUPERUSER=1 make test

test:7.1:
  image: php:7.1-cli-stretch
  only:
    - branches
  script:
    - COMPOSER_ALLOW_SUPERUSER=1 make test

build:
  image: php:7.3-cli-stretch
  stage: build
  artifacts:
    paths:
      - module-mastercard.zip
    expire_in: 30 days
  only:
    - /^build\/.*$/
  except:
    - branches
  script:
    - COMPOSER_ALLOW_SUPERUSER=1 make dist
