<?php
    /* @var \OnTap\MasterCard\Block\Checkout\Review $block */
?>
<div class="block-order-review">
    <div>
        <div>
            <h3>Billing address</h3>
            <div>
                <?php echo $block->getBillingAddressHtml() ?>
            </div>
            <a href="#">edit</a>
        </div>
        <div>
            <div>
                <h3>Shipping address</h3>
            </div>
            <div>
                <div>
                    <?php echo $block->getShippingAddressHtml() ?>
                </div>
                <a href="#">edit</a>
            </div>
        </div>
    </div>
    <div class="block order-items">
        <div class="block-content">
            <?php echo $block->getChildHtml() ?>
        </div>
    </div>
    <div>
        <a href="#" class="button">Place Order</a>
    </div>
</div>
