<?php
/**
 * Copyright (c) 2016-2021 Mastercard
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// @codingStandardsIgnoreFile

/**
 * @var \OnTap\MasterCard\Block\Adminhtml\Order\View\Info\Ach $block
 */
?>
<div class="admin__page-section-item-content">
    <div class="order-payment-additional" data-mage-init='{"OnTap_MasterCard/js/order/view/info/details": {}}'>
        <div class="primary">
            <button data-role="tns-full-payment-details-button" type="button" class="button action secondary">
                <span><?php echo __('Show Payment Details') ?></span>
            </button>
        </div>
        <div data-role="tns-full-payment-details-content" style="display: none">
            <table class="data-table admin__table-secondary">
                <tbody>
                    <?php $payment = $block->getPayment() ?>
                    <?php $info = $payment->getAdditionalInformation() ?>
                    <tr>
                        <th><?php echo __('gateway_code') ?></th>
                        <td><?php echo $block->safeValue($info['gateway_code'] ?? null) ?></td>
                    </tr>
                    <tr>
                        <th><?php echo __('txn_result') ?></th>
                        <td><?php echo $block->safeValue($info['txn_result'] ?? null) ?></td>
                    </tr>
                    <tr>
                        <th><?php echo __('accountType') ?></th>
                        <td><?php echo $block->safeValue($info['accountType'] ?? null) ?></td>
                    </tr>
                    <tr>
                        <th><?php echo __('bankAccountHolder') ?></th>
                        <td><?php echo $block->safeValue($info['bankAccountHolder'] ?? null) ?></td>
                    </tr>
                    <tr>
                        <th><?php echo __('bankAccountNumber') ?></th>
                        <td><?php echo $block->safeValue($info['bankAccountNumber'] ?? null) ?></td>
                    </tr>
                    <tr>
                        <th><?php echo __('routingNumber') ?></th>
                        <td><?php echo $block->safeValue($info['routingNumber'] ?? null) ?></td>
                    </tr>
                    <tr>
                        <th><?php echo __('secCode') ?></th>
                        <td><?php echo $block->safeValue($info['secCode'] ?? null) ?></td>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>
