<?php
    /* @var \OnTap\MasterCard\Block\Cart\AmexButton\Hpf $block */
?>
<div id="amex-express-checkout"></div>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'mage/translate',
        '<?php echo $block->getJsComponent() ?>'
    ], function ($, alert, $t) {
        'use strict';

        var config = <?php echo $block->getComponentConfig() ?>;
        $.extend(config, {
            callbacks: {
                amexExpressCheckout: function (response) {
                    if (response.status !== 'ok' || !response.session) {
                        alert({
                            content: $t('Payment could not be completed, please try again later.'),
                            closed: function () {
                                window.location.reload();
                            }
                        });
                        return;
                    }

                    $('body').trigger('processStart');

                    var params = $.param({
                        session_id: response.session.id,
                        session_version: response.session.version,
                        method: '<?php echo $block->getNameInLayout() ?>'
                    });

                    window.location.href = '<?php echo $block->getUrl('mpgs/checkout/review') ?>?' + params;
                }
            }
        });
        PaymentSession.configure(config);
    });
</script>
