<?php
    /* @var \OnTap\MasterCard\Block\Cart\AmexButton\Hpf $block */
?>
<div id="amex-express-checkout"></div>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'mage/translate',
        'OnTap_MasterCard/js/action/set-payment-information',
        '<?php echo $block->getJsComponent() ?>'
    ], function ($, alert, $t, setPaymentMethodAction) {
        'use strict';

        var config = <?php echo $block->getComponentConfig() ?>;
        $.extend(config, {
            callbacks: {
                amexExpressCheckout: function (response) {
                    if (response.status !== 'ok' || !response.session) {
                        alert({
                            content: $t('Payment could not be completed, please try again later.'),
                            closed: function () {
                                window.location.reload();
                            }
                        });
                        return;
                    }

                    $('body').trigger('processStart');

                    var params = $.param({
                        session_version: response.session.version
                    });
                    var action = setPaymentMethodAction(null, {
                        method: '<?php echo $block->getNameInLayout() ?>',
                        additional_data: {
                            session: response.session.id
                        }
                    });
                    $.when(action).done(function () {
                        window.location.href = '<?php echo $block->getUrl('mpgs/checkout/review') ?>?' + params;
                    });
                }
            }
        });
        PaymentSession.configure(config);
    });
</script>
