<?php
// @codingStandardsIgnoreFile
/**
 * @var \OnTap\MasterCard\Block\Masterpass\Review $block
 */
?>
<div class="mpgs-review view">
    <div class="block block-order-details-view">
        <div class="block-content">
            <?php if ($block->getShippingAddress()): ?>
            <div class="box box-order-shipping-method">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Shipping Method')) ?></span>
                </strong>
                <div class="box-content">
                </div>
            </div>
            <div class="box box-order-shipping-address">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Shipping Address')) ?></span>
                </strong>
                <div class="box-content">
                    <address>
                        <?= $block->escapeHtml(
                            $block->renderAddress($block->getShippingAddress()),
                            ['br']
                        );?>
                    </address>
                </div>
            </div>
            <?php endif; ?>
            <div class="box box-order-billing-address">
                <strong class="box-title"><span><?= $block->escapeHtml(__('Payment Method')) ?></span></strong>
                <div class="box-content">
                    <?= $block->escapeHtml($block->getPaymentMethodTitle()) ?><br>
                    <?= $block->escapeHtml($block->getEmail()) ?> <br>
                </div>
            </div>
        </div>
    </div>
    <button type="button" class="action checkout primary"
            value="<?= $block->escapeHtml(__('Place Order')) ?>">
        <span><?= $block->escapeHtml(__('Place Order')) ?></span>
    </button>
</div>
